GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtvc3RhcyIsImlkIjoiNjJlMmU2MTM1ZmExYjhkY2UxN2RjNDRmIiwiaWF0IjoxNjU5MDgzNjQwLCJleHAiOjE2NTkwODcyNDB9.D_n2zaxjkx2-s9uQM4QkPDzJtxnmL9oZwuP1eO64R0Y

{
    "title": "thesis3",
    "author": "Takis",
    "url": "http://test",
    "likes": 5,
    "userId": "62e2e6135fa1b8dce17dc44f"
}

###
DELETE  http://localhost:3003/api/blogs/62dfca18f67c4da1ede48fc0

###
PUT http://localhost:3003/api/blogs/62e24365b80f96fac925147a
content-type: application/json

{
    "title": "thesis2",
    "author": "kostas",
    "url": "http://test",
    "likes": 8
}

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "kostas",
    "name": "kostaspal",
    "password": "palia"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "kostas",
    "password": "palia"
}
